[package]
name = "lumine-proc"
version = "0.0.1"
authors = ["zkonge <zkonge@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "^1.0"
syn = { version = "^1.0", features = ["full"] }
quote = "^1.0"
lazy_static = "^1.4"
